In [1]:
# Install pip packages in the current Jupyter kernel 
# https://jakevdp.github.io/blog/2017/12/05/installing-python-packages-from-jupyter/
import sys
!{sys.executable} -m pip install pandas
!{sys.executable} -m pip install fuzzywuzzy

Requirement already satisfied: pandas in /Users/mackliniek/anaconda3/lib/python3.8/site-packages (1.0.5)
Requirement already satisfied: python-dateutil>=2.6.1 in /Users/mackliniek/anaconda3/lib/python3.8/site-packages (from pandas) (2.8.1)
Requirement already satisfied: pytz>=2017.2 in /Users/mackliniek/anaconda3/lib/python3.8/site-packages (from pandas) (2020.1)
Requirement already satisfied: numpy>=1.13.3 in /Users/mackliniek/anaconda3/lib/python3.8/site-packages (from pandas) (1.18.5)
Requirement already satisfied: six>=1.5 in /Users/mackliniek/anaconda3/lib/python3.8/site-packages (from python-dateutil>=2.6.1->pandas) (1.15.0)
WARNING: You are using pip version 21.0; however, version 21.0.1 is available.
You should consider upgrading via the '/Users/mackliniek/anaconda3/bin/python -m pip install --upgrade pip' command.
Requirement already satisfied: fuzzywuzzy in /Users/mackliniek/anaconda3/lib/python3.8/site-packages (0.18.0)
WARNING: You are using pip version 21.0; however, version 21.0.1 is available.
You should consider upgrading via the '/Users/mackliniek/anaconda3/bin/python -m pip install --upgrade pip' command.

In [2]:
import csv
from fuzzywuzzy import fuzz
import pandas as pd
patient_database = pd.read_csv("https://medicalprogress.dev/patient_data/patient_names.csv")

/Users/mackliniek/anaconda3/lib/python3.8/site-packages/fuzzywuzzy/fuzz.py:11: UserWarning: Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning
  warnings.warn('Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning')

In [3]:
patient_database

,Name,Birthdate,Address
0,Mr. D. Smith,05/10/1932,"28 Wood Avenue, Hockley,SS5 5NU"
1,Ms. O. Johnson,30/03/1933,"Ty-Gwyn, Harlow Common, Harlow,CM17 9NF"
2,Mr. K.O. Williams,02/11/1933,"21 Lagham Road, South Godstone,RH9 8HE"
3,Ms. Q. Brown,09/08/1939,"86 Bankside Drive, Thames Ditton,KT7 0AH"
4,Mr. D.W. Chang,19/08/1959,"8 - 12 Lands Lane, Leeds,LS1 6LD"
5,Mr. U.K. Jones,06/04/1961,"22 Silvercourt, Walsall,WS8 6HA"
6,Mr. O.P. Garcia,01/07/1966,"1 Ashdale Close, Staines,TW19 7BA"
7,Ms. A. Miller-Dalen,18/10/1968,"8A Crawford Road, Hatfield,AL10 0PG"
8,Ms. E. Davis,23/09/1969,"28 Long Bridge Street, Llanidloes,SY18 6AR"
9,Ms. Q. Wang,11/02/1974,"23 Waresley Park, Hartlebury,DY11 7XF"
10,Ms. R. Zoeng,09/01/1980,"Coach House, Colonels Lane, Upper Broughton,LE..."
11,Ms. O. Afonso-Kilo,08/09/1989,"10 Broderip, Cossington,TA7 8LA"
12,Ms. S. Rodrigez-Stylo,14/07/1998,"Bartley Mill Farm, Lamberhurst,TN3 8BH"
13,Ms. W. Martim-Burgt,21/03/2000,"4 Chestnut Grove, Withernsea,HU19 2PH"
14,Ms. A. Tomás-Adilson,17/04/2000,"91 London Road, Chatteris,PE16 6LW"
15,Ms. E. Duarte,21/11/2012,"17 Llanerch Estate, Rowen,LL32 8YA"

In [4]:
# Get input from user
name = input("Provide name: \n")
birthdate = input("Provide birthdate in format dd/mm/yyyy: \n")

# Search patient birthdate in database
for index, row in patient_database.iterrows():
        if row[1] == birthdate:
            name_patient_database = row[0]
        
# Check if patient birthdate was found
if name_patient_database != "":
    print("First name in patient database that corresponds with input birthdate =", name_patient_database)
else:
    print("Patient not found based on birthdate", birthdate)
    
# Do fuzzywuzzy comparison
Str1 = name
Str2 = name_patient_database
partial_ratio = fuzz.partial_ratio(Str1.lower(), Str2.lower())
if partial_ratio > 80:
    print("During search based on birthdate a name match was found...")
    print("Partial string ratio =", partial_ratio)
    print("Was", name_patient_database,"with birthdate", birthdate, "the patient that you were looking for?")
else:
    print("Patient not found with birthdate", birthdate, "and name", name)

Provide name:
Brown
Provide birthdate in format dd/mm/yyyy:
09/08/1939
First name in patient database that corresponds with input birthdate = Ms. Q. Brown
During search based on birthdate a name match was found...
Partial string ratio = 100
Was Ms. Q. Brown with birthdate 09/08/1939 the patient that you were looking for?